### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by AinTEAsports** [stevearc/oil.nvim#142] opened 2023-07-14 13:39 UTC
### Did you check the docs and existing issues?

- [x] I have read the docs
- [x] I have searched the existing issues

### Neovim version (nvim -v)

0.9.1

### Operating system/version

EndeavourOS Linux 6.4.3-arch1-1

### Describe the bug

When trying to set Oil floating window background to be transparent, the Oil floating window background gets transparent when you call `:lua require('oil').open_float()` for the first time, and when trying to do so a second time, the background gets orange, which makes it unusable. Also, this orange colour does not appear when searching the buffer name (with `:hi`). The bug also works with a the packer plugin manager.

### Steps To Reproduce

1. `nvim` (and open current directory with oil float)
2. Type `:highlight NormalFloat guibg=none guifg=#cad3f5`
3. Select a file
4. Call `:lua require('oil').open_float()
5. Ctrl+c (to close the oil floating window)
6. Repeat step 4 and 5 (usually 2 or 3 times) until the floating window background gets orange

### Expected Behavior

The background should be transparent everytime, also the weird thing is, when you get the orange background and get to the previous directory by typing `-`, the backround goes to transparent (and when going again to the folder you were before typing `-`, it becomes orange again).

### Directory structure

No particular directory structure used

### Repro

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "catppuccin/nvim",
  {
        "stevearc/oil.nvim",
        config = function()
            require("oil").setup({})
        end,
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("catppuccin-macchiato")
```

### Did you check the bug with a clean config?

- [X] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by stevearc** [comment] 2023-07-17 16:16
This sounds like a bad interaction between your terminal and neovim. It's highly unlikely that there's anything oil is doing to cause this behavior. My recommendation is to try to come up with a minimal repro, something like this:

```lua
local bufnr = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_lines(bufnr, 0, -1, true, { "Some sample text" })
local winid

local function show_window()
  if winid then
    vim.api.nvim_win_close(winid, true)
  end
  winid = vim.api.nvim_open_win(bufnr, true, {
    relative = "editor",
    width = vim.o.columns - 2,
    height = vim.o.lines - vim.o.cmdheight - 2,
    row = 1,
    col = 1,
    style = "minimal",
    border = "rounded",
  })
  vim.defer_fn(show_window, 2000)
end
show_window()
```
If you save that to a file and run `:source` it will repeatedly open a floating window. If that doesn't cause it to reproduce, try replicating more of your situation via highlights, switching buffers, etc. Once you get a minimal repro, file it on the Neovim repository.
As always, screenshots and video captures are very helpful when reporting visual bugs.

**Comment by AinTEAsports** [comment] 2023-07-17 17:28
Like you said, it looks like it is a bad interaction between alacritty (and particularly the tool `alacritty-themes` to change alacritty colorscheme and it seems to bad interact only with the `catppuccin` theme) and oil because when I change the alacritty theme to anything except `catppuccin`, it seems to work (or atleast it doesn't cause any visual bug, but I still can't achieve transparency with setting neovim float window background color to none).

Here is a screenshot of what the bug looks like: https://pasteboard.co/XcGmoWuhOT5L.png

**Comment by stevearc** [comment] 2023-07-29 16:49
I'm closing this as cannot repro/not the root cause. Feel free to re-open if you manage to get a minimal repro, or if you find evidence that something within oil specifically is causing this rendering bug.

**Closed by stevearc** 2023-07-29 16:49 UTC
Labels: bug
