### ISSUE TITLE
bug: Debug vim closes unexpectedly when using shortcuts

### ISSUE THREAD

**Issue by elkesrio** [stevearc/oil.nvim#324] opened 2024-03-06 09:00 UTC
### Did you check the docs and existing issues?

- [X] I have read the docs
- [X] I have searched the existing issues

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.2.1

### Describe the bug

When I open oil with the command `:Oil` everything works perfectly
But, when it's open via a mapping (`-`  or `<C-f>`), as soon as I modify an oil window (or float) vim closes.
Here is my config :

```lua
require("oil").setup({
  use_default_keymaps = true,
  prompt_save_on_select_new_entry = false,
})

local function map(m, k, v)
  vim.keymap.set(m, k, v, { noremap = true })
end

map("n", "-", ":Oil<CR>")
map("n", "<C-f>", ":lua require('oil').toggle_float()<CR>")
map("n", "q", ":lua require('oil').close()<CR>")
```

I see no logs related to this in `~/.cache/nvim/log`
How can I debug such behaviors ?

### What is the severity of this bug?

tolerable (can work around it)

### Steps To Reproduce

The bug seems related to my config. It's not reproducible with a minimal `init.lua`

### Expected Behavior

Write logs somewhere to be able to debug weird behaviors

### Directory structure

Same behavior for different projects

### Repro

```Lua
The bug seems related to my config. It's not reproducible with a minimal `init.lua`
```

### Did you check the bug with a clean config?

- [x] I have confirmed that the bug reproduces with `nvim -u repro.lua` using the repro.lua file above.

**Comment by elkesrio** [comment] 2024-03-06 09:54
Please note that everything works perfectly when the first time I open Oil is not via a mapping:

This scenario works without bugs:
- open neovim
- run `:Oil`
- close oil window
- `<C-f>` (or `-`)
- close oil window

**Comment by stevearc** [comment] 2024-03-06 17:01
Congratulations, you have found a crash in Neovim! I'll list out some options, in order of least to most effort.

1. You could try out the nightly version of Neovim and see if that fixes it. It's possible that the root cause of this crash has already been fixed.
2. You could build Neovim from source with debug symbols, and run it in gdb.
```
make CMAKE_BUILD_TYPE=Debug
gdb ./build/bin/nvim
run
```
This should give you some additional information when you hit the crash.
3. Trim your config down to try to figure out exactly what is causing the bad interaction. This will help other people reproduce the issue and should narrow the debugging search dramatically. See `:help bisect` for tips.

**Comment by stevearc** [comment] 2024-03-08 03:12
Hmmm...how are you running the nvim that you built? Are you using GDB or running it directly? Also, the issues that you're seeing with ALE and `vim.highlight` might be due to mismatched runtime files. You might need to tell it to use the nightly runtime files like so:
```
VIMRUNTIME=/path/to/neovim/runtime /path/to/neovim/build/bin/nvim
```

I think that the errors that you posted are unrelated to the original crash. We really need to find either a minimal configuration that repros the issue, or a stack trace from GDB. If running neovim that was built in debug mode doesn't produce the error, then it's possible that some difference in the compilation between debug and release modes changes the root cause. You can also try building in release mode with debug symbols to see if that will cause it to repro:
```
make CMAKE_BUILD_TYPE=RelWithDebInfo
```

**Comment by elkesrio** [comment] 2024-03-09 10:38
You're right, the issues that I'm seeing with ALE and vim.highlight are related to mismatched runtime files. I fixed those by setting `VIMRUNTIME`. 

I'm using LLDB (GDB is not supported on apple silicon) this way:

```
VIMRUNTIME=/opt/homebrew/Cellar/neovim/0.9.5/share/nvim/runtime lldb ./build/bin/nvim
```
---

The following tests are all run in LLDB with different vim versions and build types

# Using Vim 0.9.5
## Debug mode
Everything works perfectly

## RelWithDebugInfo mode
The exact same behavior described in the issue 🎉 :
It works perfectly when I open oil without mapping and closes unexpectedly when it's run via a mapping.
The problem is that I still have no logs (or they are in a log file that I can't find)
![image](https://github.com/stevearc/oil.nvim/assets/24977979/71e823b0-686c-4db2-96c0-64ac7f5759a8)


# Using the nightly version
## Debug mode
I now have this error. But it happens even when I run `oil` directly without mapping

![image](https://github.com/stevearc/oil.nvim/assets/24977979/502c1926-8131-4abd-a21b-270dabd45666)
## RelWithDebugInfo mode
Same as Debug mode

**Comment by stevearc** [comment] 2024-03-11 21:45
After you get the crash and you are back at the lldb prompt, try running `bt` or `bt all` to get the backtrace ([source](https://lldb.llvm.org/use/map.html#show-the-stack-backtrace-for-the-current-thread)).

The error in nightly is again because the VIMRUNTIME is not set to the nightly runtime dir

**Comment by stevearc** [comment] 2024-03-12 21:50
Does it seem likely to you that this could be the issue? https://github.com/stevearc/oil.nvim/issues/221#issuecomment-1905274065

**Comment by elkesrio** [comment] 2024-03-13 08:27
No. I just did the following and had the bug still:
- Open neovim
- Open oil floating window with `<C-f>` mapping
- create a file
- Tap `<ESC>`
- Vim closes

**Comment by stevearc** [comment] 2024-03-14 05:36
When you say "create a file", what steps are you actually taking? Is it:
- Enter insert mode
- Create a new line and add the text "foo"
- `<Esc>`
- `:w`
- Press `o` to confirm

Or is it some subset or different set of actions?
The reason I thought it might be the linked issue is that vim is exiting with status code 0, which should only happen if we issue a `:q` somewhere. Some ideas you can try:

- ensure you've updated oil because I did fix the linked issue and maybe it's related
- As part of your repro, run `:tabnew` after opening Neovim. If the issue is a stray call to `:quit` then it will only close the current tab instead of closing Neovim.
- monkey patch `vim.cmd.quit` and `vim.cmd.quitall` to see if they're getting called from somewhere
- right before you tap `<ESC>` and close vim, I assume you're in insert mode? You could do `<C-o>:imap <Esc>` to see if there's any mapping that will run or `<C-o>:au InsertLeave` to see if there is any autocmd that will run.

**Comment by elkesrio** [comment] 2024-03-14 08:09
I updated oil and everything worked 🔥 
Thanks a lot @stevearc

**Closed** 2024-03-14 08:09 UTC
Labels: bug, question
