### ISSUE TITLE
feature request: Preview window in float mode

### ISSUE THREAD

**Issue by sebasruiz09** [stevearc/oil.nvim#319] opened 2024-03-01 17:22 UTC
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

it is my favorite neovim plugin but I would like to have the preview in the floating window mode, as well as the option in the configuration options to adjust the width of the preview. 
that would be awesome.

### Provide background

I use oil daily and I really like the preview but to my personal taste I prefer the floating window so I would like it to be integrated. and the width adjustment for when you want to preview a file you can adjust the size of the preview and display it correctly.

### What is the significance of this feature?

no importance in functionality, but it would be a good feature that I would say many users would definitely use.

### Additional details

thank you for your work. for me it is the best plugin in my workflow <3 good wishes.

**Comment by stevearc** [comment] 2024-03-02 00:45
Closing as a duplicate of #303

**Closed by stevearc** 2024-03-02 00:45 UTC
Labels: enhancement
