### ISSUE TITLE
readme.md addition request: add example of is_always_hidden of .gitignore targets and .git folder

### ISSUE THREAD

**Issue by Arisa-Snowbell** [stevearc/oil.nvim#92] opened 2023-04-27 17:08 UTC
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

An example of is_always_hidden function that reads .gitignore and hides the targets in the file with a .git folder.

### Provide background

It's very common practice and not everyone is able to create such a function by themselves. I would appreciate that very much.
I tried but failed miserably, it didn't react at all, doesn't matter if I return true or false, it was weird.

**Comment by Arisa-Snowbell** [comment] 2023-04-27 17:18
So it appears my installation just bugged, had to remove it from plugins section and do PackerSync and add it back for the config to work, that was really weird, probably packer problem? I mean the is_always_hidden still doesn't work but other things like columns didn't work before doing this.

**Comment by nyngwang** [comment] 2023-04-28 05:41
Is this caused by my implementation? #69 I'm busy these days but you could take a look at the PR and tag/ping me when necessary, I will take a look. And sorry in advance if anything I did wrong.

**Comment by Arisa-Snowbell** [comment] 2023-04-28 07:34
Hi, I tried it again today and found out that I can't different folder from file in the is_always_hidden.
It always returns the name like it was a file name that's why my things didn't work. I included '/' as it was displayed in the buffer. Without the '/' it does work.

**Comment by stevearc** [comment] 2023-04-29 06:45
If I understand you correctly, you want all gitignored files to be hidden? That's going to be pretty involved. You'll need to find the `.gitignore` file and read it, then parse all of the patterns and convert them into vim regexes or lua patterns. Then you'll need to check the file paths in `is_always_hidden`, make it relative to the nearest gitignore, and see if any of the patterns match. It should be straightforward to get something basic working, but supporting all of [the gitignore syntax](https://git-scm.com/docs/gitignore) might be difficult.

**Comment by nyngwang** [comment] 2023-04-29 08:33
I would suggest changing the way you think:

1. Just let oil.nvim (or any other filetree-like plugin) to show almost all files(since now we have `is_always_hidden`, etc). This way you can control all of them.
2. When you want `.gitignore` file to be respected. I would suggest using a git-integrated plugin(they redirect your command/request from Neovim to git itself), e.g. [fzf-lua](https://github.com/ibhagwan/fzf-lua), instead.

I used to be a user of neo-tree and they provide some `setup` options to hide gitignored-files. This turned out to be cumbersome since I wasn't able to delete these ignored files due to "I had hidden them".

**Comment by stevearc** [comment] 2023-05-04 05:55
Closing as writing gitignore parsing logic is out of scope. The methodology is laid out, but the implementation is left as an exercise for the reader.

**Closed by stevearc** 2023-05-04 05:55 UTC
Labels: enhancement

**Comment by dmelchor-stripe** [comment] 2024-01-21 01:35
For future readers who wish to git ignore files :). This uses LazyVim 

I added a cache to avoid rerunning the git command for each file. It will run the command once and store the result. Then subsequent runs will just check against the cached result.

```lua
-- nvim/lua/plugins/oil.lua

-- @class GitCache
-- @field func function
-- @field checked boolean
-- @field result table
local GitCache = {}
GitCache.__index = GitCache

-- @param func function
-- @return GitCache
GitCache.new = function(func)
  local tbl = {}
  tbl.func = func
  tbl.checked = false
  tbl.result = {}
  setmetatable(tbl, GitCache)
  return tbl
end

-- @param dir string
GitCache._call = function(self, dir)
  local cmd = string.format('git -C %s ls-files --ignored --exclude-standard --others --directory', dir)

  local handle = io.popen(cmd)
  if handle == nil then
    return
  end

  local output = handle:read('*a')
  handle:close()

  output = string.gsub(output, '%s', '')
  output = string.gsub(output, '/$', '')

  self.result = vim.split(output, '\n')
  self.checked = true
end

-- @param dir string
-- @return table
GitCache.call = function(self, dir)
  if not self.checked then
    self:_call(dir)
  end
  return self.result
end


local function get_ignored(dir)
  local cmd = string.format('git -C %s ls-files --ignored --exclude-standard --others --directory', dir)
  local handle = io.popen(cmd)
  if handle == nil then
    return
  end

  local output = handle:read('*a')
  handle:close()
  output = string.gsub(output, '%s', '')
  output = string.gsub(output, '/$', '')

  return vim.split(output, '\n')
end

local cache = GitCache.new(get_ignored)

return {
  'stevearc/oil.nvim',
  dependencies = { "nvim-tree/nvim-web-devicons" },
  config = function()
    local oil = require('oil')
    oil.setup({
      view_options = {
        is_hidden_file = function(name, _)
          local ignored_files = cache:call(oil.get_current_dir())
          local is_ignored = vim.tbl_contains(ignored_files, name)
          return is_ignored or name == '..'
        end,
      },
    })
  end
}
```

**Comment by Rizhiy** [comment] 2024-03-19 23:35
Previous approaches seem most sane. If we want to filter by `.gitignore` we can expect that `git` is installed on the system and let it tell us what is ignored or not.

**Comment by IlyasYOY** [comment] 2024-03-20 09:46
Updated my comment so it now works not in `.git` project.

@Rizhiy you might be interested in it you took the solution

**Comment by daoye** [comment] 2024-06-13 13:38
Great! 
I was founding how to respect gitignore, It's my want. thanks! 
Can we update this solution to readme?

**Comment by stevearc** [comment] 2024-06-13 22:06
I've added this as a recipe in the new recipes section of the documentation
