### ISSUE TITLE
feature request: moving files between directories through renaming

### ISSUE THREAD

**Issue by jokesper** [stevearc/oil.nvim#350] opened 2024-04-15 18:56 UTC
### Did you check existing requests?

- [X] I have searched the existing issues

### Describe the feature

I would like better support for filenames containing slashes (relative paths):
- moving to (new) subdirectory (`bar` -> `foo/bar`)
- moving to parent directory (`bar` -> `../bar`)

### Provide background

Cutting and Pasting files feels wierd, since I often want to remain in the original directory.

### What is the significance of this feature?

nice to have

### Additional details

`..` is commonly used to refer to either:
1. strip last path component
2. the `..` symlink (useful when following relative links inside symlinked directories)
I don't think the second option is relevant for `oil.nvim`

**Comment by stevearc** [comment] 2024-04-20 00:57
Duplicate of #117

**Closed by stevearc** 2024-04-20 00:57 UTC
Labels: enhancement
